apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo-k8s
data:
  USERS_API_URL: "http://users-api-service.demo-k8s.svc.cluster.local"
  PRODUCTS_API_URL: "http://products-api-service.demo-k8s.svc.cluster.local"
  ENVIRONMENT: "development"
  LOG_LEVEL: "info"
