apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress-waf
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
  # Frontend através do BunkerWeb WAF
  - host: demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bunkerweb-service
            port:
              number: 80
  
  # Users API através do BunkerWeb WAF
  - host: users-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bunkerweb-service
            port:
              number: 80
  
  # Products API através do BunkerWeb WAF
  - host: products-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bunkerweb-service
            port:
              number: 80

